### PR TITLE
add observers for value, content

### PR DESCRIPTION
**Pull request by antonbavykin1991**

### CODE REVIEW

**Comment by antonbavykin1991** [comment]
fixed https://github.com/ChrisHonniball/ember-chosen/issues/11

**Comment by ChrisHonniball** [comment]
Haven't had a chance to test this yet. Plan on it in the next few days. Sorry for the delay on it.

**Review by armiiller — COMMENTED** [review]
Not a big fan of all the whitespace changes, but I can confirm the functionality works.

**Comment by armiiller** [comment]
@antonbavykin1991 Thanks for the good work! @ChrisHonniball thanks for the merge!

**Pull request merged**
